# .github/workflows/run-patch-bat.yml

name: Build ROM

on:
  push:
    branches:
      - main  # Adjust to your preferred branch
  pull_request:

jobs:
  run-patch:
    runs-on: windows-latest  # Specify a Windows runner for .bat files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ROM
        id: patch_run
        run: .\patch.bat > patch_log.txt
        shell: cmd

      - name: Check if ROM bad
        run: |
          if (Select-String -Pattern "Aborting." -Path patch_log.txt) { exit 1 }
        shell: pwsh
        
      - name: Generate Artifact
        if: success()  # Only upload if no "Aborting." found
        uses: actions/upload-artifact@v3
        with:
          name: Built ROM
          path: ./SMW_U.smc  # Adjust path if the file is in a different location
