# .github/workflows/run-patch-bat.yml

name: Build ROM

on:
  push:
    branches:
      - main  # Adjust to your preferred branch
  pull_request:

jobs:
  run-patch:
    runs-on: windows-latest  # Specify a Windows runner for .bat files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ROM
        run: .\patch.bat
        shell: cmd
      - name: Generate Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Built ROM
          path: ./SMW_U.smc  # Adjust path if the file is in a different location
