# .github/workflows/run-patch-bat.yml

name: Run PATCH script on Windows

on:
  push:
    branches:
      - main  # Adjust to your preferred branch
  pull_request:

jobs:
  run-patch:
    runs-on: windows-latest  # Specify a Windows runner for .bat files

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run patch.bat
        run: .\patch.bat
        shell: cmd
